input {
  file {
    path => "/home/dhis-pipelines/test.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
  }
}

filter {
  split {
    field => "[dataValues]"
  }

  mutate {
    rename => { 
      "[dataValues][dataElement]" => "dataElement"
      "[dataValues][period]" => "period"
      "[dataValues][orgUnit]" => "orgUnit"
      "[dataValues][categoryOptionCombo]" => "categoryOptionCombo"
      "[dataValues][attributeOptionCombo]" => "attributeOptionCombo"
      "[dataValues][value]" => "value"
      "[dataValues][storedBy]" => "storedBy"
      "[dataValues][created]" => "created"
      "[dataValues][lastUpdated]" => "lastUpdated"
      "[dataValues][comment]" => "comment"
      "[dataValues][followup]" => "followup"
    }

    add_field => {
      "dataSet" => "%{[dataSet]}"
      "completeDate" => "%{[completeDate]}"
      "targetIndex" => "application.easternprovince.dhis-datavalue"
    }
  }

  ruby {
    code => '
      a = []
      data_element = event.get("dataElement")
      period = event.get("period")
      org_unit = event.get("orgUnit")
      category_option_combo = event.get("categoryOptionCombo")
      attribute_option_combo = event.get("attributeOptionCombo")
      value = event.get("value")
      stored_by = event.get("storedBy")
      created = event.get("created")
      last_updated = event.get("lastUpdated")
      comment = event.get("comment")
      followup = event.get("followup")

      a.push({
        "data_element" => data_element,
        "period" => period,
        "org_unit" => org_unit,
        "category_option_combo" => category_option_combo,
        "attribute_option_combo" => attribute_option_combo,
        "value" => value,
        "stored_by" => stored_by,
        "created" => created,
        "last_updated" => last_updated,
        "comment" => comment,
        "followup" => followup
      })
      
      event.set("data_values", a)
    '
    tag_with_exception_message => true
    tag_on_exception => "ruby_processing_error"
  }

  prune {
    whitelist_names => ["data_values", "dataSet", "completeDate", "targetIndex"]
  }

  split {
    field => "data_values"
  }

  mutate {
    add_field => {
      "type_id" => "data_value"
    }
  }

  prune {
    blacklist_names => ["data_values"]
  }
}

output {
  if ![tags] {
    elasticsearch {
      hosts => ["http://167.86.74.144:9200"]
      index => "%{[targetIndex]}"
      document_id => "%{[data_values][data_element]}-%{[data_values][period]}-%{[data_values][org_unit]}-%{[data_values][category_option_combo]}-%{[data_values][attribute_option_combo]}"
    }
  }

  stdout {
    codec => rubydebug
  }
}

