
input {
  file {
    path => "/home/dhis_pipelines/test.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
  }

    http_poller {
              urls => {
                   analytics_data => {
                   method => get
                   url => "https://lg.risa.gov.rw/production/api/metadata.json?fields=%2A%5B%2A%5D"
                   headers => {
                      "Authorization" => "Basic YmFpbHk6QmFpbHlAMjAyMw=="
                    }
                        }
              }
                request_timeout => 60
                request_timeout => 60
                automatic_retries => 0
                schedule => { cron => "* * * * * UTC"}
                codec => "json"
                metadata_target => "http_poller_metadata"
        }

}

filter {
  split {
    field => "[dataValues]"
  }
  mutate {
    add_field => {
      "dataElement" => "%{[dataValues][dataElement]}"
      "period" => "%{[dataValues][period]}"
      "orgUnit" => "%{[dataValues][orgUnit]}"
      "categoryOptionCombo" => "%{[dataValues][categoryOptionCombo]}"
      "attributeOptionCombo" => "%{[dataValues][attributeOptionCombo]}"
      "value" => "%{[dataValues][value]}"
      "storedBy" => "%{[dataValues][storedBy]}"
      "created" => "%{[dataValues][created]}"
      "lastUpdated" => "%{[dataValues][lastUpdated]}"
      "comment" => "%{[dataValues][comment]}"
      "followup" => "%{[dataValues][followup]}"
    }
    remove_field => ["dataValues"]
  }
  mutate {
    convert => {
      "value" => "float"
    }
  }
  if ![value] {
    drop {}
  }
}

output {
  elasticsearch {
    hosts => ["http://167.86.74.144:9200"]
    index => "dhis2_bugesera_raw_data"
    document_id => "%{dataElement}_%{period}_%{orgUnit}"
  }
  stdout {
    codec => rubydebug
  }
}

