input {
  http_poller {
    urls => {
      dhis2_data => {
        method => get
        url => "https://lg.risa.gov.rw/production/api/dataValueSets.json?children=true&orgUnit=QoptHf4izj7&lastUpdatedDuration=150d&idScheme=name&dataSet=axfokmVEAnn&dataSet=T5LPsanyqNe&dataSet=MwVbo09Pxd3&dataSet=zOA032p00Qo&dataSet=Rxc5W3DyV1Q&dataSet=WYU9i89Ojxg&dataSet=D3yWC1VDfpd&dataSet=J8b4UvKqY2q&dataSet=ojV6pwBblac&dataSet=RnOOW97tf8H&dataSet=RjjiVFL4jG7&dataSet=kxgh0GIfcP0&dataSet=B7ZSczBbpSw&dataSet=cR5NrtGVIMA&dataSet=CfIwgh5HitX&dataSet=ht7n3Xyvj2j&dataSet=MtedaSeTg60&dataSet=U28LDUaZfrl&dataSet=ceswiOflAY8&dataSet=JbvWo5VSmEV&dataSet=uTGTsQl20VM&dataSet=TG2b2feBO8w&dataSet=Bo4w3l7Kghz&dataSet=t0j3bVKIf69&dataSet=ihxvtl9ZXbY&dataSet=MeNbfxNKPTW&dataSet=GqWnMl1eM2X&dataSet=AIcIPbFohKi&dataSet=TE15RESHNWp&dataSet=Zcm5cLtTH5H&dataSet=XZEVnsOJN50&dataSet=iCpC92bvLbc&dataSet=L2atfpmdZZW&dataSet=DS1Pvp1P5UH&dataSet=eirz6vXH8hv&dataSet=rA125WukGA2&dataSet=bMvAlKu2kvs&dataSet=cYRYT4OPZ4P&dataSet=siJDftz93Kc&dataSet=WHW0rgXHKa0&dataSet=gSZGoS2ze5y&dataSet=xAOFh1HEhXZ&dataSet=f9YGUasA6jm&dataSet=h3acc8Q8gvU&dataSet=AfHfZd4tIqS&dataSet=xL98WCYMuPj&dataSet=FHb1pbKLYHw&dataSet=r41qjU4fgCV&dataSet=U3b27qdGkTi&dataSet=DLJQddkuHjm&dataSet=wx0hOYJmU3u&dataSet=tlnn1YuPyl8&dataSet=U70EjU4cLfH&dataSet=xXYFFmP2XHl&dataSet=FOAkGUi6sj3&dataSet=TcFotoIjQMO&dataSet=fPFpYHmxovQ"
        headers => {
          Accept => "application/json"
          Authorization => "Basic YmFpbHk6QmFpbHlAMjAyMw=="  # Use Base64 encoded credentials
        }
      }
    }
    request_timeout => 60
    schedule => { cron => "*/2 * * * *" }  # Poll the API every minute
    codec => "json"
  }
}


filter {
  if [dataValues] {
    # Split each dataValues entry into individual events
    split { field => "dataValues" }

    # Rename fields inside dataValues to root-level fields
    mutate {
      rename => { "[dataValues][dataElement]" => "dataElement" }
      rename => { "[dataValues][period]" => "period" }
      rename => { "[dataValues][orgUnit]" => "orgUnit" }
      rename => { "[dataValues][categoryOptionCombo]" => "categoryOptionCombo" }
      rename => { "[dataValues][value]" => "value" }

      # Remove the original dataValues field after splitting
      remove_field => ["dataValues"]
    }
  }
}



output {
    elasticsearch{

       hosts => ["http://localhost:9200"]
       index => "application.allrawdata"
       document_id => "%{[dataElement]}-%{[orgUnit]}-%{[period]}"




}
stdout { codec => rubydebug }
}

