services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms200m -Xmx200m
      - xpack.security.enabled=false

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - TELEMETRY_ENABLED=false

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.1
    container_name: logstash
    environment:
      - xpack.monitoring.enabled=false
      - LS_JAVA_OPTS=-Xms500m -Xmx500m
      - queue.type=persisted
      - queue.max_bytes=4gb
      - pipeline.batch.size=50
      - pipeline.batch.delay=5
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    volumes:
      - /home/alain/Alain/ELK-DOCKER/pipelines:/usr/share/logstash/customPipelines
    command: logstash -f /usr/share/logstash/customPipelines/test2.conf
