input {
  http_poller {
    urls => {
      analytics_data => {
        method => get
        url => "https://lg.risa.gov.rw/production/api/analytics.json?dimension=dx:k5nVAOse14P;yOTCaWwCWYr;GexRAjT5eRC;E5ahkJEjDK8;D4rBbOLU7M4;mKHgS4Do4LS;wjAAxTa8yPM;qfpzFpj5OLS;Dv1afXdIWjP;hp5Lg4XPVE6;qhLSdlFyCRO;HDjE619fnL8;kbYQR5jrv9f;YQYSLYAcmKU;m3qvWyyZaHK;Tl8bYdKEIma;WQOkHjmeCNf;mra7Y3bTTdb&dimension=pe:2024Q1&dimension=ou:QvFN6czJQuE;QMwKjwbyHU0;qeyBLoAsGMY;NUTBDE82Fdd;Z0gqNaQwwUB;qcfRERmqi5u;CcDFZe89eSq"
        headers => {
          "Authorization" => "Basic YmFpbHk6QmFpbHlAMjAyMw=="
        }
      }
    }
    request_timeout => 60
    schedule => { cron => "* * * * * UTC" }
    codec => "json"
  }
}



filter{

  split {
    field => "rows"
  }

  mutate {
    add_field => {
      "data_element_id" => "%{[rows][0]}"
      "pe" => "%{[rows][1]}"
      "organisation_unit_id" => "%{[rows][2]}"
      "value" => "%{[rows][3]}"
    }
    remove_field => ["rows"]
  }

  if [data_element_id] == "dx" or [data_element_id] == "ou" or [data_element_id] == "value" {
    drop {}
  }

  ruby {
    code => '
      metadata_items = event.get("[metaData][items]")
      data_element_id = event.get("data_element_id")
      organisation_unit_id = event.get("organisation_unit_id")
      pe = event.get("pe")
      event.set("data_element", metadata_items[data_element_id]["name"])
      event.set("organisation_unit", metadata_items[organisation_unit_id]["name"])
      event.set("period",metadata_items[pe]["name"])
    '
  }

  mutate {
    remove_field => ["headers", "metaData", "dimensions"]
    remove_field => ["data_element_id", "organisation_unit_id","pe"]
  }

  mutate {
    convert => { "value" => "float" }
  }
}


  

output {
   elasticsearch{
   hosts => ["http://167.86.74.144:9200"]
   index => "eastern_master_imihingo"
   document_type => "_doc"
}

  stdout {
    codec => rubydebug
  }
}

