input {
  http_poller {
    urls => {
      DHIS2_meta_data => {
        method => get
        url => "https://lg.risa.gov.rw/production/api/metadata.json?&skipSharing=true&dataSets=true&dataElements=true&categoryOptionCombos=true&fields=id,name,lastUpdated"
        headers => {
          Authorization => "Basic YmFpbHk6QmFpbHlAMjAyMw=="
        }

      }
    }
    request_timeout => 60
    automatic_retries => 3
    schedule => { cron => "* * * * * UTC" }
    codec => "json"
  }
}

filter {
  if [http_request_failure] {
    drop {}
  } else {

    ruby {
      code => '
        def transform_metadata(event)
          metadata_types = ["dataElements", "dataSets", "categoryOptionCombos"]
          transformed_data = []

          metadata_types.each do |type|
            items = event.get(type)
            next if items.nil?

            items.each do |item|
              data = {
                "type" => "meta_data_#{type}",
                "id" => item["id"],
                "name" => item["name"],
                "lastUpdated" => item["lastUpdated"]
              }

              transformed_data << data
            end
          end

          event.set("meta_data", transformed_data)
        end

        transform_metadata(event)
      '
      tag_with_exception_message => true
      tag_on_exception => "transformation_exception"
    }

    prune {
      whitelist_names => ["meta_data"]
    }

    split {
      field => "[meta_data]"
    }

    mutate {
      add_field => { "doc_id" => "%{[meta_data][id]}" }
    }

  }
}

 output {
   if ![tags] and ![http_request_failure] {

        elasticsearch{
          hosts => ["$ELASTICSEARCH_HOSTS"]
          user => "$ELASTICSEARCH_USERNAME"
          password => "$ELASTICSEARCH_PASSWORD"
          index => "application.metadata"
          document_id => "%{doc_id}" 
          cacert => "/etc/logstash/security/ca/ca.crt"
          ssl => "true"
          ssl_certificate_verification => "true"

        
        }
        stdout {
       codec => rubydebug
     }
 }else{
    elasticsearch{
      hosts => ["$ELASTICSEARCH_HOSTS"]
      user => "$ELASTICSEARCH_USERNAME"
      password => "$ELASTICSEARCH_PASSWORD"
      cacert => "/etc/logstash/security/ca/ca.crt"
      ssl => "true"
      ssl_certificate_verification => "true"
      index => "error.connection"  
    
    }
  }
 }
