input {
  http_poller {
    urls => {
      analytics_data => {
        method => get
        url => "https://lg.risa.gov.rw/production/api/metadata.json?skipSharing=true&organisationUnits=true&fields=id,name,path,level,parent"
        headers => {
          Accept => "application/json"
          Authorization => "Basic YmFpbHk6QmFpbHlAMjAyMw=="
        }
      }
    }
    request_timeout => 60
    schedule => { cron => "* * * * * UTC" }
    codec => "json"
    tags => ["http_request"]
  }
}

filter {
   if [http_request_failure] {
    drop { }
  }
 else {
           
    ruby {
      code => '
        units = event.get("organisationUnits")
        return unless units

        unit_dict = {}
        units.each do |unit|
          unit_dict[unit["id"]] = unit
        end

        enriched_units = []
        units.each do |unit|
          parent_id = unit["parent"] ? unit["parent"]["id"] : nil
          enriched_unit = {
            "type" => "organisationUnit",
            "id" => unit["id"],
            "name" => unit["name"],
            "level" => unit["level"],
            "path" => unit["path"],
            "parent_id" => parent_id
          }

          if parent_id && unit_dict[parent_id]
            parent_unit = unit_dict[parent_id]
            enriched_unit["parent_level"] = parent_unit["level"]
            enriched_unit["parent_name"] = parent_unit["name"]
            enriched_unit["parent_path"] = parent_unit["path"]
          end

          enriched_units << enriched_unit
        end
        event.set("master_data", enriched_units)
      '
      tag_with_exception_message => true
      tag_on_exception => "ruby_enrichment_exception"
    }

    prune {
      whitelist_names => ["master_data"]
    }

    split {
      field => "master_data"
    }

    mutate {
      rename => { "[master_data][name]" => "organisation_name" }
      add_field => { "organisation_level_%{[master_data][level]}" => "%{organisation_name}" }
      replace => { "id" => "%{[master_data][id]}" }  # Ensure the id field is correctly set
    }
  }
}


output {
  if ![tags] and ![http_request_failure] {
   
      elasticsearch{
        hosts => ["http://167.86.74.144:9200"]
        index => "dhis-metadata"
        document_id => "%{id}"
      }
       stdout {
      codec => rubydebug
    }
}else{
  elasticsearch{
    hosts => ["http://167.86.74.144:9200"]
    index => "pipelines.error"
  }
}



}
