input {
  http_poller {
    urls => {
      DHIS2_meta_data => {
        method => get
        url => "https://lg.risa.gov.rw/production/api/metadata.json?skipSharing=true&organisationUnits=true&fields=id,name,path,level,parent"
        headers => {
          Accept => "application/json"
          Authorization => "Basic YmFpbHk6QmFpbHlAMjAyMw=="
        }
      }
    }
    request_timeout => 180
    schedule => { cron => "* * * * * UTC" }
    codec => "json"
    tags => ["http_request"]
  }
}
filter {
  if [http_request_failure] {
    drop { }
  } else {
    ruby {
      code => '
        units = event.get("organisationUnits")
        return unless units

        unit_dict = {}
        units.each do |unit|
          unit_dict[unit["id"]] = unit
        end

        def map_ids_to_names(path, unit_dict)
          path.split("/").map { |id| unit_dict[id] ? unit_dict[id]["name"] : id }.join("/")
        end

        enriched_units = []
        units.each do |unit|
          parent_id = unit["parent"] ? unit["parent"]["id"] : nil
          enriched_unit = {
            "type" => "organisationUnit",
            "organisationUnit_id" => unit["id"],
            "name" => unit["name"],
            "OrganisationUnitLevel" => unit["level"],
            "hierarchy" => map_ids_to_names(unit["path"], unit_dict),

          }

          if parent_id && unit_dict[parent_id]
            parent_unit = unit_dict[parent_id]
            enriched_unit["parent_level"] = parent_unit["level"]
            enriched_unit["parent_hierarchy"] = map_ids_to_names(parent_unit["path"], unit_dict)
          end

          enriched_units << enriched_unit
        end

        event.set("meta_data", enriched_units)
      '
      tag_with_exception_message => true
      tag_on_exception => "ruby_enrichment_exception"
    }

    prune {
      whitelist_names => ["meta_data"]
    }

    split {
      field => "meta_data"
    }

    mutate {
      rename => { "[meta_data][name]" => "organisationUnit_name" }
      replace => { "id" => "%{[meta_data][organisationUnit_id]}" }
    }
  }
}
output {
  if ![tags] and ![http_request_failure]{
    elasticsearch {
        hosts => ["http://localhost:9200"]
        index => "application.metadata"
        document_id => "%{id}"
    }

    stdout { codec => rubydebug }
  }else{
    elasticsearch{
      hosts => ["http://localhost:9200"]
      index => "error.connection"  
    
    }
  }
 }

